# Builds the Oracle R2DBC Driver using Maven

name: Build Oracle R2DBC

on:
  push:
    branches:
    - main
    - development
  pull_request:
    branches:
    - main
    - development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Maven
      run: mvn -B package --file pom.xml -DskipTests=true
